apiVersion: v1
kind: Service
metadata:
  name: webapps-svc
  labels:
    name: webapps-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: webapps